export const API_BASE_URL = '/api';

export type EndpointId = string | number;

export function encodeEndpointId(id: EndpointId) {
  return encodeURIComponent(String(id));
}

export const endpoints = {
  auth: {
    login: '/login',
    register: '/register',
    logout: '/logout',
    me: '/me',
    permissions: '/me/permissions',
  },
  public: {
    products: '/public/products',
    product: (product: EndpointId) => `/public/products/${encodeEndpointId(product)}`,
    packages: '/public/packages',
    registrationPackages: '/public/registration-packages',
    news: '/public/news',
    newsItem: (news: EndpointId) => `/public/news/${encodeEndpointId(news)}`,
    faqs: '/public/faqs',
    statuses: '/public/statuses',
    legalSettings: '/public/legal-settings',
  },
  dashboard: {
    overview: '/dashboard/overview',
    profile: '/dashboard/profile',
    profileAvatar: '/dashboard/profile/avatar',
    structure: '/dashboard/structure',
    transactions: '/dashboard/transactions',
    bonuses: '/dashboard/bonuses',
    earningsSummary: '/dashboard/earnings-summary',
    notifications: '/dashboard/notifications',
    packages: '/dashboard/packages',
    products: '/dashboard/products',
    depositProducts: '/dashboard/deposit-products',
    orders: '/dashboard/orders',
    withdrawals: '/dashboard/withdrawals',
    supportTickets: '/dashboard/support-tickets',
    supportTicket: (ticket: EndpointId) => `/dashboard/support-tickets/${encodeEndpointId(ticket)}`,
    closeSupportTicket: (ticket: EndpointId) => `/dashboard/support-tickets/${encodeEndpointId(ticket)}/close`,
    productCatalog: '/products',
    orderCheckout: '/orders',
    order: (order: EndpointId) => `/orders/${encodeEndpointId(order)}`,
    orderTipTopPayIntent: (order: EndpointId) => `/orders/${encodeEndpointId(order)}/payment/tiptoppay/intent`,
    withdrawalRequests: '/withdrawals',
    activatePackage: (pkg: EndpointId) => `/packages/${encodeEndpointId(pkg)}/activate`,
    upgradePackage: (pkg: EndpointId) => `/packages/${encodeEndpointId(pkg)}/upgrade`,
    depositPurchase: '/deposits/purchase',
  },
  admin: {
    overview: '/admin/overview',
    partners: '/admin/partners',
    partnersSearch: '/admin/partners/search',
    partnersBulkCreate: '/admin/partners/bulk-create',
    partner: (user: EndpointId) => `/admin/partners/${encodeEndpointId(user)}`,
    partnerStatus: (user: EndpointId) => `/admin/partners/${encodeEndpointId(user)}/status`,
    partnerPackage: (user: EndpointId) => `/admin/partners/${encodeEndpointId(user)}/package`,
    partnerBlock: (user: EndpointId) => `/admin/partners/${encodeEndpointId(user)}/block`,
    partnerUnblock: (user: EndpointId) => `/admin/partners/${encodeEndpointId(user)}/unblock`,
    partnerNote: (user: EndpointId) => `/admin/partners/${encodeEndpointId(user)}/note`,
    partnerPassword: (user: EndpointId) => `/admin/partners/${encodeEndpointId(user)}/change-password`,
    partnerTransactions: (user: EndpointId) => `/admin/partners/${encodeEndpointId(user)}/transactions`,
    partnerBinaryBonusCalculate: (user: EndpointId) => `/admin/partners/${encodeEndpointId(user)}/binary-bonus/calculate`,
    partnerTree: (user: EndpointId) => `/admin/partners/${encodeEndpointId(user)}/tree`,
    partnerDeletePreview: (user: EndpointId) => `/admin/partners/${encodeEndpointId(user)}/delete-preview`,
    structure: '/admin/structure',
    users: '/admin/users',
    user: (user: EndpointId) => `/admin/users/${encodeEndpointId(user)}`,
    products: '/admin/products',
    product: (product: EndpointId) => `/admin/products/${encodeEndpointId(product)}`,
    packages: '/admin/packages',
    package: (pkg: EndpointId) => `/admin/packages/${encodeEndpointId(pkg)}`,
    orders: '/admin/orders',
    order: (order: EndpointId) => `/admin/orders/${encodeEndpointId(order)}`,
    orderStatus: (order: EndpointId) => `/admin/orders/${encodeEndpointId(order)}/status`,
    transactions: '/admin/transactions',
    bonuses: '/admin/bonuses',
    withdrawals: '/admin/withdrawals',
    approveWithdrawal: (withdrawal: EndpointId) => `/admin/withdrawals/${encodeEndpointId(withdrawal)}/approve`,
    rejectWithdrawal: (withdrawal: EndpointId) => `/admin/withdrawals/${encodeEndpointId(withdrawal)}/reject`,
    news: '/admin/news',
    newsItem: (news: EndpointId) => `/admin/news/${encodeEndpointId(news)}`,
    faqs: '/admin/faqs',
    faq: (faq: EndpointId) => `/admin/faqs/${encodeEndpointId(faq)}`,
    supportTickets: '/support/tickets',
    supportTicket: (ticket: EndpointId) => `/support/tickets/${encodeEndpointId(ticket)}`,
    replySupportTicket: (ticket: EndpointId) => `/support/tickets/${encodeEndpointId(ticket)}/reply`,
    updateSupportTicketStatus: (ticket: EndpointId) => `/support/tickets/${encodeEndpointId(ticket)}/status`,
    assignSupportTicket: (ticket: EndpointId) => `/support/tickets/${encodeEndpointId(ticket)}/assign`,
    closeSupportTicket: (ticket: EndpointId) => `/admin/support-tickets/${encodeEndpointId(ticket)}/close`,
    reportsSummary: '/admin/reports/summary',
    settings: '/admin/settings',
    statuses: '/admin/statuses',
  },
} as const;
