<?php

return [
    'roles' => [
        'user' => [
            'label' => 'Partner',
            'redirect_after_login' => '/dashboard',
            'allowed_routes' => [
                '/dashboard',
                '/dashboard/structure',
                '/dashboard/transactions',
                '/dashboard/bonuses',
                '/dashboard/package',
                '/dashboard/package-status',
                '/dashboard/products',
                '/dashboard/news',
                '/dashboard/profile',
                '/dashboard/support',
            ],
            'menu' => [
                ['path' => '/dashboard', 'label' => 'Обзор', 'icon' => 'layout-dashboard'],
                ['path' => '/dashboard/structure', 'label' => 'Моя структура', 'icon' => 'users'],
                ['path' => '/dashboard/transactions', 'label' => 'Транзакции', 'icon' => 'credit-card'],
                ['path' => '/dashboard/bonuses', 'label' => 'Бонусы и вывод', 'icon' => 'gift'],
                ['path' => '/dashboard/package', 'label' => 'Пакет и статус', 'icon' => 'star'],
                ['path' => '/dashboard/products', 'label' => 'Продукты', 'icon' => 'shopping-bag'],
                ['path' => '/dashboard/news', 'label' => 'Новости', 'icon' => 'newspaper'],
                ['path' => '/dashboard/profile', 'label' => 'Профиль', 'icon' => 'user-circle'],
                ['path' => '/dashboard/support', 'label' => 'Поддержка', 'icon' => 'help-circle'],
            ],
        ],

        'support' => [
            'label' => 'Support',
            'redirect_after_login' => '/support',
            'allowed_routes' => [
                '/support',
                '/support/tickets',
                '/support/profile',
            ],
            'menu' => [
                ['path' => '/support', 'label' => 'Обращения', 'icon' => 'message-square'],
                ['path' => '/support/profile', 'label' => 'Профиль', 'icon' => 'user-circle'],
            ],
        ],

        'admin' => [
            'label' => 'Admin',
            'redirect_after_login' => '/admin',
            'allowed_routes' => [
                '/admin',
                '/admin/partners',
                '/admin/partners/:id',
                '/admin/structure',
                '/admin/transactions',
                '/admin/withdrawals',
                '/admin/bonuses',
                '/admin/packages',
                '/admin/statuses',
                '/admin/products',
                '/admin/news',
                '/admin/support',
            ],
            'menu' => [
                ['path' => '/admin', 'label' => 'Обзор', 'icon' => 'bar-chart'],
                ['path' => '/admin/partners', 'label' => 'Партнёры', 'icon' => 'users'],
                ['path' => '/admin/structure', 'label' => 'Структура', 'icon' => 'network'],
                ['path' => '/admin/transactions', 'label' => 'Транзакции', 'icon' => 'credit-card'],
                ['path' => '/admin/withdrawals', 'label' => 'Заявки на вывод', 'icon' => 'arrow-up-circle'],
                ['path' => '/admin/bonuses', 'label' => 'Бонусы', 'icon' => 'gift'],
                ['path' => '/admin/packages', 'label' => 'Пакеты', 'icon' => 'package'],
                ['path' => '/admin/statuses', 'label' => 'Статусы', 'icon' => 'trophy'],
                ['path' => '/admin/products', 'label' => 'Продукты', 'icon' => 'shopping-bag'],
                ['path' => '/admin/news', 'label' => 'Новости', 'icon' => 'newspaper'],
                ['path' => '/admin/support', 'label' => 'Поддержка', 'icon' => 'message-square'],
            ],
        ],

        'accountant' => [
            'label' => 'Бухгалтер',
            'redirect_after_login' => '/admin',
            'allowed_routes' => [
                '/admin',
                '/admin/transactions',
                '/admin/withdrawals',
                '/admin/reports',
            ],
            'menu' => [
                ['path' => '/admin', 'label' => 'Обзор', 'icon' => 'bar-chart'],
                ['path' => '/admin/transactions', 'label' => 'Транзакции', 'icon' => 'credit-card'],
                ['path' => '/admin/withdrawals', 'label' => 'Заявки на вывод', 'icon' => 'arrow-up-circle'],
                ['path' => '/admin/reports', 'label' => 'Отчёты', 'icon' => 'pie-chart'],
            ],
        ],

        'super_admin' => [
            'label' => 'Super Admin',
            'redirect_after_login' => '/admin',
            'allowed_routes' => [
                '/admin',
                '/admin/partners',
                '/admin/partners/:id',
                '/admin/partners/bulk-create',
                '/admin/structure',
                '/admin/transactions',
                '/admin/withdrawals',
                '/admin/bonuses',
                '/admin/packages',
                '/admin/statuses',
                '/admin/products',
                '/admin/news',
                '/admin/support',
                '/admin/reports',
                '/admin/settings',
            ],
            'menu' => [
                ['path' => '/admin', 'label' => 'Обзор', 'icon' => 'bar-chart'],
                ['path' => '/admin/partners', 'label' => 'Партнёры', 'icon' => 'users'],
                ['path' => '/admin/structure', 'label' => 'Структура', 'icon' => 'network'],
                ['path' => '/admin/transactions', 'label' => 'Транзакции', 'icon' => 'credit-card'],
                ['path' => '/admin/withdrawals', 'label' => 'Заявки на вывод', 'icon' => 'arrow-up-circle'],
                ['path' => '/admin/bonuses', 'label' => 'Бонусы', 'icon' => 'gift'],
                ['path' => '/admin/packages', 'label' => 'Пакеты', 'icon' => 'package'],
                ['path' => '/admin/statuses', 'label' => 'Статусы', 'icon' => 'trophy'],
                ['path' => '/admin/products', 'label' => 'Продукты', 'icon' => 'shopping-bag'],
                ['path' => '/admin/news', 'label' => 'Новости', 'icon' => 'newspaper'],
                ['path' => '/admin/support', 'label' => 'Поддержка', 'icon' => 'message-square'],
                ['path' => '/admin/reports', 'label' => 'Отчёты', 'icon' => 'pie-chart'],
                ['path' => '/admin/settings', 'label' => 'Настройки', 'icon' => 'settings'],
            ],
        ],
    ],

    'api_permissions' => [
        'dashboard.access' => ['user'],
        'support.manage' => ['support', 'admin', 'super_admin'],
        'admin.overview' => ['admin', 'accountant', 'super_admin'],
        'admin.transactions.read' => ['admin', 'accountant', 'super_admin'],
        'admin.withdrawals.read' => ['admin', 'accountant', 'super_admin'],
        'admin.read' => ['admin', 'super_admin'],
        'admin.catalog.write' => ['super_admin'],
        'admin.settings' => ['super_admin'],
        'admin.reports' => ['accountant', 'super_admin'],
        'admin.partners.create' => ['super_admin'],
        'admin.partners.manage' => ['admin', 'super_admin'],
        'admin.withdrawals.manage' => ['super_admin'],
    ],
];
